Fix/client and server are not blocked by exceptions
eyecan-ai/shiva pull request #21
Opened 2024-06-27 12:52 UTC by domef

The client can set a timeout when sending a message to the server. In this way, if the server raises an exception, the client will not be stopped indefinitely.

2024-06-27 14:54 UTC, lykius commented on shiva/__init__.py
> +        responose_message = await ShivaMessage.receive_message_async(
now it's a good time to fix this typo :)

2024-06-27 15:01 UTC, lykius requested changes
see comment

2024-06-27 15:04 UTC, lykius approved these changes
Lucertola Giaguaro Topo Minotauro

2024-07-01 12:46 UTC, mmarcoo commented
@domef @lykius può essere conclusa?

2024-07-01 12:58 UTC, merged

2024-07-01 12:59 UTC, lykius commented
merged